## Task 1. Generate random and non-random arrays in different ways.

In [1]:
import numpy as np

In [2]:
a = np.array([[0,0,0,0], [1,1,1,1], [2,2,2,2]])   # auto typed
a

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [3]:
a = np.array([0,1,0,0], dtype='bool')    # manual type system
a

array([False,  True, False, False])

In [4]:
a = np.arange(0, 20, 3)    # auto create array with start, stop, step
a

array([ 0,  3,  6,  9, 12, 15, 18])

In [5]:
a = np.ones(10, dtype=complex)     # auto create array of 1's
a

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.+0.j])

In [8]:
a = np.zeros((2,2,3), dtype=bool)    # auto create array of 0's with shape
a

array([[[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False]]])

In [11]:
a = np.linspace(0, 100, 9)   # proportional array of values
a

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [12]:
a = np.random.random(5)    # array of random 0to1 values
a

array([0.62268106, 0.38941783, 0.73464668, 0.5086445 , 0.92229549])

In [14]:
a = np.random.randint(1, 5, 10)    # array of random 1to5 values
a

array([4, 3, 3, 4, 1, 1, 4, 4, 4, 4])

In [15]:
a = np.empty(10)   # empty array of size 10
a

array([4.67341201e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       1.84708169e-104, 2.56945978e+184, 3.21442411e-057, 6.50573416e-091,
       4.54973138e+174, 7.05483132e-308])

## Task 2. Getting array properties, indexation, slicing

In [36]:
a = np.array([[0,0,0,0], [1,1,1,1], [2,2,4,3]])
print('Number of dimensions: ', a.ndim)
print('Shape of array: ', a.shape)
print('Type of elements: ', a.dtype)
print('Bytesize of array: ', a.nbytes)
print('Size of each element: ', a.itemsize)

Number of dimensions:  2
Shape of array:  (3, 4)
Type of elements:  int64
Bytesize of array:  96
Size of each element:  8


In [37]:
print('First subarray:', a[0])
print('Last subarray:', a[-1])
print('First element of second subarray:', a[1, 0])
print('Slice of last two elements of last subarray:', a[-1, -2:])

First subarray: [0 0 0 0]
Last subarray: [2 2 4 3]
First element of second subarray: 1
Slice of last two elements of last subarray: [4 3]


## Task 3. Arithmetic operations on arrays, methods (reduce, accumulate, outer)

In [47]:
a = np.array([[1,2,3,4], [5,6,7,8], [3,4,5,6]])
print('Increment every element:\n', a+1)
print('Decrement every element:\n', a-1)
print('Double every element:\n', a*2)
print('Divide every element by 2:\n', a/2)
print('Raise to power 2 every element:\n', a**2)
print('Modulo 3 every element:\n', a%3)
print('Negate every element:\n', -a)

Increment every element:
 [[2 3 4 5]
 [6 7 8 9]
 [4 5 6 7]]
Decrement every element:
 [[0 1 2 3]
 [4 5 6 7]
 [2 3 4 5]]
Double every element:
 [[ 2  4  6  8]
 [10 12 14 16]
 [ 6  8 10 12]]
Divide every element by 2:
 [[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [1.5 2.  2.5 3. ]]
Raise to power 2 every element:
 [[ 1  4  9 16]
 [25 36 49 64]
 [ 9 16 25 36]]
Modulo 3 every element:
 [[1 2 0 1]
 [2 0 1 2]
 [0 1 2 0]]
Negate every element:
 [[-1 -2 -3 -4]
 [-5 -6 -7 -8]
 [-3 -4 -5 -6]]


In [60]:
a = np.arange(0, 101)
print('Sum of 0 to 100:', np.add.reduce(a))
print('Sum of 0 to 100 with middle results:\n', np.add.accumulate(a))
print('Product of vectors:\n', np.outer(a, a))

Sum of 0 to 100: 5050
Sum of 0 to 100 with middle results:
 [   0    1    3    6   10   15   21   28   36   45   55   66   78   91
  105  120  136  153  171  190  210  231  253  276  300  325  351  378
  406  435  465  496  528  561  595  630  666  703  741  780  820  861
  903  946  990 1035 1081 1128 1176 1225 1275 1326 1378 1431 1485 1540
 1596 1653 1711 1770 1830 1891 1953 2016 2080 2145 2211 2278 2346 2415
 2485 2556 2628 2701 2775 2850 2926 3003 3081 3160 3240 3321 3403 3486
 3570 3655 3741 3828 3916 4005 4095 4186 4278 4371 4465 4560 4656 4753
 4851 4950 5050]
Product of vectors:
 [[    0     0     0 ...     0     0     0]
 [    0     1     2 ...    98    99   100]
 [    0     2     4 ...   196   198   200]
 ...
 [    0    98   196 ...  9604  9702  9800]
 [    0    99   198 ...  9702  9801  9900]
 [    0   100   200 ...  9800  9900 10000]]


## Task 4. Array statistics with pandas csv

In [74]:
import pandas as pd
file_path = './iris.csv'
data = pd.read_csv(file_path)
width_arr = np.array(data['petal_width'])
width_arr

[0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.3,
 0.4,
 0.4,
 0.4,
 0.4,
 0.4,
 0.4,
 0.4,
 0.5,
 0.6,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.1,
 1.1,
 1.1,
 1.2,
 1.2,
 1.2,
 1.2,
 1.2,
 1.3,
 1.3,
 1.3,
 1.3,
 1.3,
 1.3,
 1.3,
 1.3,
 1.3,
 1.3,
 1.3,
 1.3,
 1.3,
 1.4,
 1.4,
 1.4,
 1.4,
 1.4,
 1.4,
 1.4,
 1.4,
 1.5,
 1.5,
 1.5,
 1.5,
 1.5,
 1.5,
 1.5,
 1.5,
 1.5,
 1.5,
 1.5,
 1.5,
 1.6,
 1.6,
 1.6,
 1.6,
 1.7,
 1.7,
 1.8,
 1.8,
 1.8,
 1.8,
 1.8,
 1.8,
 1.8,
 1.8,
 1.8,
 1.8,
 1.8,
 1.8,
 1.9,
 1.9,
 1.9,
 1.9,
 1.9,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.1,
 2.1,
 2.1,
 2.1,
 2.1,
 2.1,
 2.2,
 2.2,
 2.2,
 2.3,
 2.3,
 2.3,
 2.3,
 2.3,
 2.3,
 2.3,
 2.3,
 2.4,
 2.4,
 2.4,
 2.5,
 2.5,
 2.5]

In [77]:
print('Minimal width:', np.min(width_arr))
print('Maximal width:', np.max(width_arr))
print('Medium value:', np.mean(width_arr))
print('Standard deviation:', np.std(width_arr))
print('Dispersion:', np.var(width_arr))
print('Median:', np.median(width_arr))
print('Percentile 25:', np.percentile(width_arr, 25))
print('Percentile 75:', np.percentile(width_arr, 75))

Minimal width: 0.1
Maximal width: 2.5
Medium value: 1.1986666666666668
Standard deviation: 0.7606126185881716
Dispersion: 0.5785315555555555
Median: 1.3
Percentile 25: 0.3
Percentile 75: 1.8
